pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Fabric'
                    url = uri('https://maven.fabricmc.net')
                }
            }
            filter { includeGroupAndSubgroups('net.fabricmc') }
        }
    }
    plugins {
        id "org.jetbrains.kotlin.kapt" version '2.4.10'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'unbidden'
includeBuild('build-logic')

include('survival:common')
include('survival:fabric')
include('survival:neoforge')

include('fx:common')
include('fx:fabric')
include('fx:neoforge')
