style:
  WildcardImport:
    active: false
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    active: true
    excludeGuardClauses: true
  ForbiddenComment:
    comments:
      - value: 'FIXME:'
        reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
      - value: 'STOPSHIP:'
        reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'

complexity:
  TooManyFunctions:
    ignorePrivate: true

ktlint:
  MaximumLineLength:
    active: true
    maxLineLength: 100
  FunctionSignature:
    maxLineLength: 100
  ClassSignature:
    maxLineLength: 100
  ArgumentListWrapping:
    maxLineLength: 100
  ParameterListWrapping:
    maxLineLength: 100
